namespace AlpacaApiClient.Model
{
	public enum AlpacaKycResults
	{
		IDENTITY_VERIFICATION,
		TAX_IDENTIFICATION,
		ADDRESS_VERIFICATION,
		DATE_OF_BIRTH,
		PEP,
		FAMILY_MEMBER_PEP,
		CONTROL_PERSON,
		AFFILIATED,
		OTHER
	}
}
